"""Discovery of canonical stages generated by official processing engines."""

from __future__ import annotations

import re
from pathlib import Path

from insar_pilot.domain.workflows import OfficialStageDescriptor

_RUN_FILE_PATTERN = re.compile(r"^run_(?P<sequence>[0-9]+)(?:_(?P<label>.+))?$")
_ID_CHARACTER_PATTERN = re.compile(r"[^a-z0-9]+")


class OfficialPlanError(ValueError):
    """An upstream-generated execution plan is ambiguous or malformed."""


class Isce2TopsStageDiscovery:
    """Project ISCE2 topsStack run files into ordered, one-step tasks.

    The generated ``run_files/run_*`` files are the source of truth.  This
    service deliberately does not recreate ESD, burst resampling, or burst
    merging as application-owned algorithms.
    """

    def discover(self, work_dir: str | Path) -> tuple[OfficialStageDescriptor, ...]:
        run_dir = Path(work_dir).expanduser() / "run_files"
        if not run_dir.is_dir():
            return ()

        parsed: list[tuple[int, Path, str]] = []
        for path in run_dir.iterdir():
            if not path.is_file():
                continue
            match = _RUN_FILE_PATTERN.fullmatch(path.name)
            if match is None:
                continue
            sequence = int(match.group("sequence"))
            label = match.group("label") or f"stage_{sequence}"
            parsed.append((sequence, path.resolve(), label))

        parsed.sort(key=lambda item: (item[0], item[1].name))
        sequences = [sequence for sequence, _, _ in parsed]
        duplicates = sorted({item for item in sequences if sequences.count(item) > 1})
        if duplicates:
            joined = ", ".join(str(item) for item in duplicates)
            raise OfficialPlanError(f"ISCE2 run-file sequence numbers are duplicated: {joined}")

        stages: list[OfficialStageDescriptor] = []
        previous_id: str | None = None
        for sequence, path, label in parsed:
            slug = _ID_CHARACTER_PATTERN.sub("_", label.lower()).strip("_") or "stage"
            stage_id = f"sentinel1.isce2.run_{sequence:02d}_{slug}"
            stages.append(
                OfficialStageDescriptor(
                    stage_id=stage_id,
                    sequence=sequence,
                    display_name=label.replace("_", " "),
                    source_path=str(path),
                    depends_on=(previous_id,) if previous_id is not None else (),
                )
            )
            previous_id = stage_id
        return tuple(stages)


__all__ = ["Isce2TopsStageDiscovery", "OfficialPlanError"]
