export const zhLabels: Record<string, string> = {
  'Add pipeline':'添加流水线','Add selection to project':'将所选数据添加到工程','Add to project':'添加到工程',
  'Attach processing dataset':'绑定处理数据集','Cancel':'取消','Create pipeline':'创建流水线','Create project':'创建工程',
  'Create project from selection':'从所选数据创建工程','Direction':'轨道方向','Dismiss':'关闭','Download only':'仅下载',
  'Frame':'帧号','Frequency':'频段','From':'开始日期','Full log':'完整日志','Go to Data':'打开数据页','History':'历史',
  'Import references':'导入数据引用','Input role':'输入用途','Inspect available inputs':'查看可用输入','Load more':'加载更多',
  'Map':'地图','Metadata and provenance':'元数据与来源','Mission':'卫星任务','Mission filters':'任务专属筛选',
  'Open':'打开','Open QC workspace':'打开质检工作区','Open map':'打开地图','Path':'轨道号','Pipeline':'流水线',
  'Plan execution':'预览执行计划','Plan rerun':'预览重跑计划','Polarization':'极化','Processing acquisitions · reference first':'处理影像 · 首项为参考影像',
  'Processor Python executable':'处理器 Python 路径','Profile':'工程类型','Project':'工程','Project directory':'工程目录',
  'Properties':'属性','Relative orbit':'相对轨道','Scientific parameters · JSON':'科学参数 · JSON',
  'Search':'检索','Submit this plan':'提交此计划','To':'结束日期','Ubuntu file paths · one per line':'Ubuntu 文件路径 · 每行一项',
  'Use this run':'采用此运行','Validated ISCE3 runconfig template':'已验证的 ISCE3 配置模板','AOI · west, south, east, north':'研究区域 · 西、南、东、北',
  'home':'首页','pipeline':'流水线','new':'新建工程','open':'打开工程','explore':'数据检索','data':'工程数据','products':'成果',
  'map':'地图','qc':'质量检查','history':'运行历史','events':'事件','log':'完整日志','files':'文件','library':'数据仓库',
  'downloads':'下载','compute':'计算环境','post':'后处理','project':'工程','jobs':'任务',
  'Quality control':'质量检查','Run history':'运行历史','Structured events':'结构化事件','Files':'文件',
  'Data Library':'数据仓库','Downloads':'下载','Compute':'计算环境','Post-processing':'后处理',
  'INSPECTOR':'属性面板','DATA EXPLORER':'数据检索','POST-PROCESSING':'后处理',
  'unpack topo reference':'参考 SLC 解包与几何','unpack secondary slc':'辅影像 SLC 解包','average baseline':'基线计算',
  'extract burst overlaps':'Burst 重叠区提取','overlap geo2rdr':'重叠区几何映射','overlap resample':'重叠区重采样',
  'pairs misreg':'配对错配估计','timeseries misreg':'日期级错配估计','fullBurst geo2rdr':'完整 Burst 几何映射',
  'fullBurst resample':'完整 Burst 重采样','extract stack valid region':'公共有效区','merge reference secondary slc':'SLC 与几何合并',
  'generate burst igram':'Burst 干涉图','merge burst igram':'Burst 干涉图合并','filter coherence':'滤波与相干性','unwrap':'解缠',
  'Official NISAR InSAR':'官方 NISAR InSAR',
}
