import { expect, test } from '@playwright/test'
const headers={Authorization:'Bearer local-picker-test-session'}
test.beforeEach(async({page})=>{
  await page.addInitScript(()=>{sessionStorage.setItem('pilot-token','local-picker-test-session')})
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Recent projects',exact:true})).toBeVisible()
})

test('always starts at project selection, closes cleanly, and keeps five guarded pages',async({page},info)=>{
  const projects=await (await page.request.get('/api/v1/projects',{headers})).json()
  await page.evaluate(id=>localStorage.setItem('pilot-project',id),projects[0].project_id)
  await page.reload()
  await expect(page.getByRole('heading',{name:'Choose your project',exact:true})).toBeVisible()
  await expect(page.getByTestId('primary-pages').getByRole('tab')).toHaveCount(5)
  await expect(page.getByRole('tab',{name:'4 Run',exact:true})).toBeDisabled()
  await expect(page.locator('.inspector')).not.toBeVisible()
  await page.screenshot({path:info.outputPath('home.png')})
  await page.locator('.project-card').filter({hasText:'Picker existing'}).click()
  await expect(page.locator('.project-name')).toHaveText('Picker existing')
  await expect(page.getByRole('heading',{name:'Project data',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Close project',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Choose your project',exact:true})).toBeVisible()
  await expect(page.getByRole('tab',{name:'2 Data & preparation',exact:true})).toBeDisabled()
  await expect(page.locator('.project-tree-scroll')).toHaveCount(0)
  await page.getByRole('button',{name:'Jobs',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Background activity'})).toBeVisible()
  await expect(page.getByRole('tab',{name:'4 Run',exact:true})).toBeDisabled()
})

test('new project has data and processing with hidden records and can reopen from its pilot',async({page},info)=>{
  const projects=await (await page.request.get('/api/v1/projects',{headers})).json()
  const parent=projects.find((p:any)=>p.name==='Picker existing').path.replace(/\/Existing Project$/,'')
  const name='Layout '+info.project.name+' '+Date.now()
  await page.locator('.home').getByRole('button',{name:'New project',exact:true}).click()
  await page.getByLabel('Project name',{exact:true}).fill(name)
  await page.getByLabel('Save location',{exact:true}).fill(parent)
  await expect(page.getByText('Project file to create',{exact:true})).toBeVisible()
  await page.screenshot({path:info.outputPath('new-project.png')})
  await page.getByRole('button',{name:'Create project',exact:true}).click()
  await expect(page.locator('.project-name')).toHaveText(name)
  const created=(await (await page.request.get('/api/v1/projects',{headers})).json()).find((p:any)=>p.name===name)
  expect(created.storage_layout_version).toBe(2)
  const files=await (await page.request.get(`/api/v1/projects/${created.project_id}/files`,{headers})).json()
  expect(files.map((f:any)=>f.name)).toEqual(expect.arrayContaining(['data','processing','products',name+'.pilot']))
  expect(files.map((f:any)=>f.name)).not.toContain('.insar_pilot')
  await page.reload()
  await expect(page.getByRole('heading',{name:'Choose your project',exact:true})).toBeVisible()
  await page.locator('.home').getByRole('button',{name:'Open project',exact:true}).click()
  await page.getByLabel('Project file (.pilot)',{exact:true}).fill(created.project_file)
  await expect(page.getByText('Ready to open',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Open',exact:true}).click()
  await expect(page.locator('.project-name')).toHaveText(name)
})

test('home supports Chinese dark theme and long paths without page overflow',async({page},info)=>{
  await page.getByRole('button',{name:'Change language',exact:true}).click()
  await page.getByRole('button',{name:'Toggle theme',exact:true}).click()
  await expect(page.getByRole('heading',{name:'选择工程，开始工作'})).toBeVisible()
  await page.setViewportSize({width:1440,height:900})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
  await page.screenshot({path:info.outputPath('home-zh-dark.png')})
})
